mysite/home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.HomeView.as_view()),
]

mysite/items/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='items'
urlpatterns = [
    path('', views.ItemListView.as_view(), name='all'),
    path('item/<int:pk>', views.ItemDetailView.as_view(), name='item_detail'),
    path('item/create',
        views.ItemCreateView.as_view(success_url=reverse_lazy('items:all')), name='item_create'),
    path('item/<int:pk>/update',
        views.ItemUpdateView.as_view(success_url=reverse_lazy('items:all')), name='item_update'),
    path('item/<int:pk>/delete',
        views.ItemDeleteView.as_view(success_url=reverse_lazy('items:all')), name='item_delete'),
        path('item_picture/<int:pk>', views.stream_file, name='item_picture'),
    path('item/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='item_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('items:all')), name='item_comment_delete'),
    path('item/<int:pk>/addreview',
        views.addReview, name='create_review'),
    path('item/<int:pk>/review',
        views.ReviewCreateView.as_view(), name='review_create'),
]

# We use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve

urlpatterns = [
    path('', include('items.urls')),
    # path('', include('home.urls')),
    # path('shop/', include('items.urls')),
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

mysite/items/models.py
from django.db import models
from django.forms import ModelForm
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import User
from django.conf import settings


class Item(models.Model):
    title = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Title must be greater than 2 characters")]
    )
    text = models.TextField()
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    picture = models.BinaryField(null=True, blank=True, editable=True)
    content_type = models.CharField(max_length=256, null=True, blank=True,
                                    help_text='The MIMEType of the file')
    comments = models.ManyToManyField(settings.AUTH_USER_MODEL,
        through='Comment', related_name='comments_owned')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        return self.title
class Comment(models.Model) :
    text = models.TextField(
        validators=[MinLengthValidator(3, "Comment must be greater than 3 characters")]
    )

    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        if len(self.text) < 15 : return self.text
        return self.text[:11] + ' ...'

class Review(models.Model):
    item = models.ForeignKey(Item, on_delete = models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    subject = models.CharField(max_length = 50, blank = True)
    review = models.CharField(max_length = 250, blank = True)
    rate = models.IntegerField(default = 1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.subject

mysite/items/forms.py
from django import forms
from django.forms import ModelForm
from items.models import Item, Comment, Review
from django.core.files.uploadedfile import InMemoryUploadedFile
from items.humanize import naturalsize
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


# Create the form class.
class CreateForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)

    # Call this 'picture' so it gets copied from the form to the in-memory model
    # It will not be the "bytes", it will be the "InMemoryUploadedFile"
    # because we need to pull out things like content_type
    picture = forms.FileField(required=False, label='File to Upload <= '+max_upload_limit_text)
    upload_field_name = 'picture'

    # Hint: this will need to be changed for use in the items application :)
    class Meta:
        model = Item
        fields = ['title', 'text', 'picture', 'price']  # Picture is manual

    # Validate the size of the picture
    def clean(self):
        cleaned_data = super().clean()
        item = cleaned_data.get('picture')
        if item is None:
            return
        if len(item) > self.max_upload_limit:
            self.add_error('picture', "File must be < "+self.max_upload_limit_text+" bytes")

    # Convert uploaded File object to a picture
    def save(self, commit=True):
        instance = super(CreateForm, self).save(commit=False)

        # We only need to adjust picture if it is a freshly uploaded file
        f = instance.picture   # Make a copy
        if isinstance(f, InMemoryUploadedFile):  # Extract data from the form to the model
            bytearr = f.read()
            instance.content_type = f.content_type
            instance.picture = bytearr  # Overwrite with the actual image data

        if commit:
            instance.save()

        return instance

class CommentForm(forms.Form):
    comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True)

class ReviewForm(forms.Form):
    rating = forms.IntegerField()
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'id-exampleForm'
        self.helper.form_class = 'blueForms'
        self.helper.form_method = 'post'
        self.helper.form_action = 'submit_survey'

        self.helper.add_input(Submit('submit', 'Submit'))
    # class Meta:
    #     model = Review
    #     fields = ['subject', 'review', 'rate']
    # def save(self, commit=True):
    #     instance = super(ReviewForm, self).save(commit=False)

    #     if commit:
    #         instance.save()

    #     return instance


# https://docs.djangoproject.com/en/3.0/topics/http/file-uploads/
# https://stackoverflow.com/questions/2472422/django-file-upload-size-limit
# https://stackoverflow.com/questions/32007311/how-to-change-data-in-django-modelform
# https://docs.djangoproject.com/en/3.0/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other

mysite/items/views.py
from items.models import Item, Comment, Review
from items.owner import OwnerListView, OwnerDetailView, OwnerCreateView, OwnerUpdateView, OwnerDeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from items.forms import CreateForm, CommentForm, ReviewForm
from django.urls import reverse_lazy, reverse
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages

class ItemListView(OwnerListView):
    model = Item
    # By convention:
    # template_name = "items/item_list.html"


class ItemDetailView(OwnerDetailView):
    model = Item
    template_name = "items/item_detail.html"
    def get(self, request, pk) :
        x = Item.objects.get(id=pk)
        comments = Comment.objects.filter(item=x).order_by('-updated_at')
        comment_form = CommentForm()
        context = { 'item' : x, 'comments': comments, 'comment_form': comment_form }
        return render(request, self.template_name, context)


class ItemCreateView(OwnerCreateView):
    # model = Item
    # fields = ['title', 'text', 'price']
    template_name = 'items/item_form.html'
    success_url = reverse_lazy('items:all')

    def get(self, request, pk=None):
        form = CreateForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        form = CreateForm(request.POST, request.FILES or None)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        # Add owner to the model before saving
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect(self.success_url)


class ItemUpdateView(OwnerUpdateView):
    # model = Item
    # fields = ['title', 'text', 'price']
    template_name = 'items/item_form.html'
    success_url = reverse_lazy('items:all')

    def get(self, request, pk):
        item = get_object_or_404(Item, id=pk, owner=self.request.user)
        form = CreateForm(instance=item)
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        item = get_object_or_404(Item, id=pk, owner=self.request.user)
        form = CreateForm(request.POST, request.FILES or None, instance=item)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        item = form.save(commit=False)
        item.save()

        return redirect(self.success_url)

class ItemDeleteView(OwnerDeleteView):
    model = Item

def stream_file(request, pk):
    item = get_object_or_404(Item, id=pk)
    response = HttpResponse()
    response['Content-Type'] = item.content_type
    response['Content-Length'] = len(item.picture)
    response.write(item.picture)
    return response

class CommentCreateView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        f = get_object_or_404(Item, id=pk)
        comment = Comment(text=request.POST['comment'], owner=request.user, item=f)
        comment.save()
        return redirect(reverse('items:item_detail', args=[pk]))

class CommentDeleteView(OwnerDeleteView):
    model = Comment
    template_name = "items/item_comment_delete.html"

    # https://stackoverflow.com/questions/26290415/deleteview-with-a-dynamic-success-url-dependent-on-id
    def get_success_url(self):
        item = self.object.item
        return reverse('items:item_detail', args=[item.id])

def addReview(request, id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            data = Review()
            data.name = form.cleaned_data['name']
            data.subject = form.cleaned_data['subject']
            data.review = form.cleaned_data['review']
            data.ip = request.METS.get('REMOTE_ADDR')
            data.item_id = id
            current_user = request.user
            data.owner = current_user.id
            data.save()
            messages.success(request, "Your review has been sent. Thank you.")
            return HttpResponseRedirect(url)
    return HttpResponseRedirect(url)

# class ReviewCreateView(OwnerCreateView):
#     model = Review
#     fields = ['subject', 'review', 'rating']

# class ReviewCreateView(OwnerCreateView):
#     # model = Item
#     # fields = ['title', 'text', 'price']
#     template_name = 'items/review_form.html'
#     success_url = reverse_lazy('items:all')

#     def get(self, request, pk=None):
#         form = ReviewForm()
#         ctx = {'form': form}
#         return render(request, self.template_name, ctx)

#     def post(self, request, pk=None):
#         form = Review(request.POST, request.FILES or None)

#         if not form.is_valid():
#             ctx = {'form': form}
#             return render(request, self.template_name, ctx)

#         # Add owner to the model before saving
#         item = form.save(commit=False)
#         item.owner = self.request.user
#         item.save()
#         return redirect(self.success_url)

class ReviewCreateView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        f = get_object_or_404(Item, id=pk)
        comment = Review(text=request.POST['rating'], owner=request.user, item=f)
        comment.save()
        return redirect(reverse('items:item_detail', args=[pk]))

mysite/items/templates/items/item_comment_delete.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Delete Comment</h1>

<p>Are you sure you want to delete</p>
<p>{{ comment.text }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit"  class="btn btn-primary" value="Yes, delete.">
  <a href="{% url 'items:item_detail' comment.item.id %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}

mysite/items/templates/items/item_confirm_delete.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Delete Item</h1>

<p>Are you sure you want to delete the item: {{ item }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

mysite/items/templates/items/item_detail.html
{% extends "base_menu.html" %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->
{% block head %}
<style>
.overlay{
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 10;
  display: none;
  background-color: rgba(0,0,0,0.5); /*dim the background*/
}
</style>
{% endblock %}
{% block content %}
{% if pic.content_type %}
<div id="overlay" class="overlay" style="text-align: center;"
   onclick="document.getElementById('overlay').style.display = 'none';" >
<img style="width:90%;margin-top: 50px; border:3px solid black;" src="{% url 'pics:pic_picture' pic.id %}">
</div>
{% endif %}
<span style="float: right;">
({{ item.updated_at|naturaltime }})
{% if item.owner == user %}
<a href="{% url 'items:item_update' item.id %}"><i class="fa fa-pencil"></i></a>
<a href="{% url 'items:item_delete' item.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</span>
<h1>{{ item.title }}</h1>
{% if item.content_type %}
<img style="float:right; max-width:50%;" src="{% url 'items:item_picture' item.id %}"
    onclick="document.getElementById('overlay').style.display = 'block';">
{% endif %}
<p>
{{ item.text }}
</p>
<p>
{{ item.price }}
</p>


{% if user.is_authenticated %}
<br clear="all"/>
<p>
{% load crispy_forms_tags %}
<form method="post" action="{% url 'items:item_comment_create' item.id %}">
    {% csrf_token %}
    {{ comment_form|crispy }}
<input type="submit" value="Submit">
<input type="submit" value="All Items" onclick="window.location.href='{% url 'items:all' %}';return false;">
</form>
</p>
{% endif %}
{% for comment in comments %}
<p> {{ comment.text }}
({{ comment.updated_at|naturaltime }})
{% if user == comment.owner %}
<a href="{% url 'items:item_comment_delete' comment.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</p>
{% endfor %}
<p>
{% load crispy_forms_tags %}
<form method="post" action="{% url 'items:review_create' item.id %}">
    {% csrf_token %}
    {% crispy example_form example_form.helper %}
<input type="submit" value="Submit">
<input type="submit" value="All Items" onclick="window.location.href='{% url 'items:all' %}';return false;">
</form>
</p>

{% endblock %}

mysite/items/templates/items/item_form.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'items:all' %}';return false;">
  </form>
</p>
<script>
$("#upload_form").submit(function() {
  console.log('Checking file size');
  if (window.File && window.FileReader && window.FileList && window.Blob) {
      var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
      if (file && file.size > {{ form.max_upload_limit }} ) {
          alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
      return false;
    }
  }
});
</script>
{% endblock %}

mysite/items/templates/items/item_list.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Items</h1>
<p>
{% if item_list %}
<ul>
  {% for item in item_list %}
    <li>
        <a href="{% url 'items:item_detail'  item.id %}">{{ item.title }}</a>
        {% if user.is_superuser %}
        (<a href="{% url 'items:item_update' item.id %}">Edit</a> |
        <a href="{% url 'items:item_delete' item.id %}">Delete</a>)
        {% endif %}
    </li>
  {% endfor %}
</ul>
{% else %}
  <p>There are no items in the database.</p>
{% endif %}
</p>
<p>
{% if user.is_superuser %}
    <a href="{% url 'items:item_create' %}">Add an Item</a> |
{% endif %}
{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'items:all' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'items:all' %}">Login</a>
{% endif %}
</p>
{% endblock %}

mysite/items/templates/items/review_form.html
{% extends "base_bootstrap.html" %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form method="post" action="{% url 'items:review_create' item.id %}">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'items:all' %}';return false;">
  </form>
</p>
{% endblock %}